sudo: false
language: node_js
node_js:
  - "8.3"
notifications:
  email:
    on_success: always
    on_failure: always
  slack: srboeingdotnet:UIU3Bl3s8QViLrC2yS7GV9NI
mono: none
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - echo "No Tests"
after_success:
  - /bin/bash ./deploy.sh
